POST http://localhost:5000/api/users/register Content-Type: application/json

{
"nickname":"rayhan", "email": "rayhan@hotmail.com", "password": "Rayhan1234"
}

### GET http://localhost:5000/api/users/hello

### POST http://localhost:5000/api/auth/login Content-Type: application/json

{
"email":"rayhan@hotmail.com", "password":"Rayhan1234"
}

### GET http://localhost:5000/api/users Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjMsIm5pY2tuYW1lIjoidGltbyIsImVtYWlsIjoidGltb0A4OWhvdG1haWwuY29tIiwiaWF0IjoxNjU1ODAwMDAxLCJleHAiOjE2NTU4MDAwMjF9.CpbSNeHzgWlErCOTmpkrcvw7AbTg3483zEhHQ6fpRps

### GET http://localhost:5000/api/auth/refresh_token

### DELETE http://localhost:5000/api/auth/refresh_token

### GET http://localhost:5000/api/users/lobby

### GET http://localhost:5000/api/users/lobby/:id